<a href="https://colab.research.google.com/github/zxxt2002/MAT494-Xiantong-Zhao/blob/main/HW_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Gram-Schmidt Process

In [13]:
# L-20 MCS 507 Fri 11 Oct 2013 : gramschmidt.py

import numpy as np

def gramschmidt(A):
    """
    Applies the Gram-Schmidt method to A
    and returns Q and R, so Q*R = A.
    """
    R = np.zeros((A.shape[1], A.shape[1]))
    Q = np.zeros(A.shape)
    for k in range(0, A.shape[1]):
        R[k, k] = np.sqrt(np.dot(A[:, k], A[:, k]))
        Q[:, k] = A[:, k]/R[k, k]
        for j in range(k+1, A.shape[1]):
            R[k, j] = np.dot(Q[:, k], A[:, j])
            A[:, j] = A[:, j] - R[k, j]*Q[:, k]
    return Q, R

def main():
    """
    Prompts for n and generates a random matrix.
    """
    cols = int(input('give number of columns : '))
    rows = int(input('give number of rows : '))
    A = np.random.rand(rows, cols)
    print('A = ')
    print(A)
    Q, R = gramschmidt(A)
    print('Q = ')
    print(Q)
    print('R = ')
    print(R)
    print('Q^T*Q = ')
    print(np.dot(Q.transpose(), Q))
    print('Q*R =')
    print(np.dot(Q, R))

main()

give number of columns : 5
give number of rows : 5
A = 
[[0.7786489  0.072619   0.78185892 0.8657164  0.78287507]
 [0.51606937 0.97979891 0.60244506 0.38159557 0.82770614]
 [0.50311078 0.78435442 0.94667427 0.66503746 0.1581384 ]
 [0.5448276  0.1932458  0.47709034 0.02408683 0.68273656]
 [0.8791362  0.90472007 0.56008566 0.78592614 0.86516882]]
Q = 
[[ 0.52550752 -0.63029248  0.2585512   0.35095994  0.36952894]
 [ 0.34829348  0.58408079 -0.01884055 -0.20084659  0.70487372]
 [ 0.33954777  0.38570854  0.73019197  0.10690146 -0.43741056]
 [ 0.36770231 -0.28786244 -0.0059506  -0.8637204  -0.18942514]
 [ 0.59332606  0.1730467  -0.63212387  0.28115283 -0.37335174]]
R = 
[[ 1.48170839  1.25359613  1.44988221  1.28882696  1.51775795]
 [ 0.          0.92997332  0.18380172  0.06280696  0.00418272]
 [ 0.          0.          0.52517163  0.20530156 -0.24866631]
 [ 0.          0.          0.          0.49844416 -0.22102777]
 [ 0.          0.          0.          0.          0.35121214]]
Q^T*Q = 
[[