pythagorean theory in 3d coordinate system 

In [43]:
import numpy as np

#create a random vector a which is one of side of right angle
a = np.random.rand(3)
print('vector a: ',a)

#create a vecotor b perpendicular to the a, b will be one of the side of right angle
b = np.empty_like(a)
b[0] = a[1]
b[1] = -a[0]
b[2] = 0
print('vector b: ',b)

# the third side of triangle will be c
c = a - b
print('vector c: ',c)

#get c^2, a^2, b^2
d = np.dot(c,c)
e = np.dot(a,a)
f = np.dot(b,b)

#print c^2
print('c^2: ', np.dot(c,c))
#print a^2
print('a^2: ', np.dot(a,a))
#print b^2
print('b^2: ', np.dot(b,b))
#calculate if the a^2 + b^2 be equal to c^2 (pythagorean theory) by using c^2 - a^2 - b^2
print('c^2 - a^2 - b^2 = ', d - e - f)

vector a:  [0.5167534  0.50146772 0.91029023]
vector b:  [ 0.50146772 -0.5167534   0.        ]
vector c:  [0.01528568 1.01822112 0.91029023]
c^2:  1.8656362083653928
a^2:  1.3471322568683566
b^2:  0.5185039514970362
c^2 - a^2 - b^2 =  0.0


Eigenvalues and eigenvectors

In [42]:
from numpy.linalg import eig
from numpy.linalg import eigvals
#create a square matrix a
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

# use eig(a) to Calculate the eigenvalues and eigenvectors of the square matrix.
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)
# use eigvals(a) to Calculate the eigenvalues of the square matrix.
w = eigvals(a)
print('E-value:', w)

# verify that the eigenvalues and eigenvectors are correct by the definition of engenvalues and eignvectors     
if np.allclose(w * v, np.dot(a, v)):
        print('Correct')
else:
        print('Wrong')

E-value: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
E-vector [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
E-value: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Correct


matrix inversion

In [60]:
#create a random square matrix f and e
f = np.random.randint(100, size=(3, 3))
e = np.random.randint(10, size=(4, 4))

#find trace and 
print('matrix f: ', f)
print('trace of f: ', np.trace(f))
print('inverse matrix of f: ', np.linalg.inv(f))

#prove find the correct inverse matrix
print('result of dot product of matrix f and its inverse matrix: ')
print(np.round(np.dot(f,np.linalg.inv(f)),3), '\n')

print('matrix e: ', e)
print('trace of e: ',np.trace(e))
print('invert matrix of e: ', np.linalg.inv(e))

#prove find the correct inverse matrix
print('result of dot product of matrix e and its inverse matrix: ')
print(np.round(np.dot(e,np.linalg.inv(e)),3))

matrix f:  [[ 5  2 29]
 [93 96 82]
 [21 80  0]]
trace of f:  101
inverse matrix of f:  [[-0.05127403  0.0181335  -0.02047835]
 [ 0.01345943 -0.00476004  0.01787557]
 [ 0.04239487 -0.00279819  0.00229795]]
result of dot product of matrix f and its inverse matrix: 
[[ 1. -0. -0.]
 [-0.  1. -0.]
 [-0. -0.  1.]] 

matrix e:  [[9 0 8 6]
 [4 6 6 1]
 [1 3 7 9]
 [5 2 8 6]]
trace of e:  28
invert matrix of e:  [[ 0.33596838  0.11857708  0.11067194 -0.52173913]
 [ 0.17193676  0.23715415  0.22134387 -0.54347826]
 [-0.43675889 -0.1541502  -0.34387352  0.97826087]
 [ 0.24505929  0.02766798  0.29249012 -0.52173913]]
result of dot product of matrix e and its inverse matrix: 
[[ 1. -0.  0.  0.]
 [-0.  1.  0. -0.]
 [-0.  0.  1. -0.]
 [-0. -0.  0.  1.]]
